---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: envoygateway
  namespace: envoy-gateway-system
spec:
  interval: 5m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: v0.0.0-latest
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoygateway
  namespace: envoy-gateway-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: envoygateway
    namespace: envoy-gateway-system